### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by jibaku** [abarmat/python-oembed#4]
I'm planning to convert a project that use to Python 3, and I would like to know if a python3-compatible pull request would have a chance to be merged ?

Thanks

**Comment by mkody** [comment]
@abarmat Can you please publish the 0.2.3 to Pypi?
`pip install python-oembed` still gives us the 0.2.2.

And thanks for this library!

**Comment by abarmat** [comment]
@mkody I've just published the last release, thank you.
