### ISSUE TITLE
python-oembed-0.2.2.macosx-10.10-x86_64.tar.gz in pypi is broken

### ISSUE THREAD

**Issue by idgserpro** [abarmat/python-oembed#7]
The [mac package on pypi](https://pypi.python.org/packages/any/p/python-oembed/python-oembed-0.2.2.macosx-10.10-x86_64.tar.gz#md5=8288a72060c388dfba5dab9bf4fc34af) is broken: a whole mac os x strucuture from your machine is downloaded instead of an egg.

```
Users/
└── abarmat
    └── .virtualenvs
        └── oony
            └── lib
                └── python2.7
                    └── site-packages
                        ├── oembed
                        │   ├── __init__.py
                        │   └── __init__.pyc
                        └── python_oembed-0.2.2-py2.7.egg-info
                            ├── dependency_links.txt
                            ├── PKG-INFO
                            ├── SOURCES.txt
                            └── top_level.txt
```

**Comment by abarmat** [comment]
That file shouldn't be there, I deleted it. Thank you!

**Comment by idgserpro** [comment]
If you use eggs download cache (download-cache in buildout) and had already downloaded the python-oembed-0.2.2.macosx-10.10-x86_64.tar.gz, you must delete it from the cache directory to function. Thank you for fix @abarmat!
